style:
    - ./www/css/style.css
script:
    - ./www/lib/ionic/js/ionic.bundle.js
    - ./www/lib/validate/validate.js
    - ./www/lib/pluralize/pluralize.js
    - ./www/lib/ngstorage/ngStorage.js
    - ./www/lib/angular-http-auth/src/http-auth-interceptor.js
    - ./www/lib/angular-oauth2/dist/angular-oauth2.js
    - ./www/lib/angular-translate/angular-translate.js
    - ./www/lib/angular-translate-loader-partial/angular-translate-loader-partial.js
    - ./www/lib/angular-resource/angular-resource.js
    - ./www/lib/angular-md5/angular-md5.js
    - ./www/lib/chance/chance.js
    - ./www/lib/moment/moment.js
    - ./www/lib/underscore/underscore.js
    - ./www/lib/jquery/dist/jquery.js
    - ./www/lib/jquery-ui/jquery-ui.js
    - ./www/lib/jqueryui-touch-punch/jquery.ui.touch-punch.js
    - ./www/lib/ngCordova/dist/ng-cordova.js
    - ./www/lib/ng-cordova-oauth/dist/ng-cordova-oauth.js
    - ./src/index/cordova.js
    - ./www/js/app.js
