#!/bin/bash

sudo rm -rf node_modules/*
echo "removed node_modules"
sudo rm -rf platforms/*
echo "removed platforms"
sudo rm -rf plugins/*
echo "removed plugins"
sudo rm -rf www/lib/*
echo "removed lib"
sudo npm install
bower install
ionic platform add ios && ionic platform add android@5.0.0
ionic plugin add cordova-plugin-device
ionic plugin add cordova-plugin-console
ionic plugin add cordova-plugin-splashscreen
ionic plugin add cordova-plugin-statusbar
ionic plugin add cordova-plugin-inappbrowser
ionic plugin add com.ionic.keyboard
ionic plugin add cordova-plugin-app-version
ionic plugin add cordova-plugin-whitelist
ionic plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git
ionic plugin add cordova-plugin-file
ionic plugin add cordova-plugin-file-transfer
ionic plugin add https://github.com/danwilson/google-analytics-plugin.git
ionic plugin add https://github.com/devgeeks/Canvas2ImagePlugin.git
ionic plugin add https://github.com/VersoSolutions/CordovaClipboard.git
ionic plugin add https://github.com/apache/cordova-plugin-camera.git#2.0.0
ionic plugin add https://github.com/litehelpers/Cordova-sqlite-storage.git
ionic plugin add cordova-plugin-vibration
ionic browser add crosswalk
gulp remove && gulp build
